export {default as SearchOutlined} from "@ant-design/icons/SearchOutlined";
export {default as FireFilled} from "@ant-design/icons/FireFilled";
export {default as SunOutlined} from "@ant-design/icons/SunOutlined";
export {default as MoonOutlined} from "@ant-design/icons/MoonOutlined";
export {default as MenuOutlined} from "@ant-design/icons/MenuOutlined";
export {default as UserOutlined} from "@ant-design/icons/UserOutlined";
export {default as LogoutOutlined} from "@ant-design/icons/LogoutOutlined";
export {default as MenuUnfoldOutlined} from "@ant-design/icons/MenuUnfoldOutlined";
export {default as LoadingOutlined} from "@ant-design/icons/LoadingOutlined";
export {default as BankOutlined} from "@ant-design/icons/BankOutlined";
export {default as DashboardOutlined} from "@ant-design/icons/DashboardOutlined";
export {default as UsergroupAddOutlined} from "@ant-design/icons/UsergroupAddOutlined";
export {default as MailOutlined} from "@ant-design/icons/MailOutlined";
export {default as LoginOutlined} from "@ant-design/icons/LoginOutlined";
export {default as LockOutlined} from "@ant-design/icons/LockOutlined";
export {default as UserAddOutlined} from "@ant-design/icons/UserAddOutlined";
export {default as DeleteOutlined} from "@ant-design/icons/DeleteOutlined";
export {default as EditOutlined} from "@ant-design/icons/EditOutlined";
export {default as ReloadOutlined} from "@ant-design/icons/ReloadOutlined";
export {default as SaveOutlined} from "@ant-design/icons/SaveOutlined";
export {default as EnvironmentOutlined} from "@ant-design/icons/EnvironmentOutlined";
export {default as HomeOutlined} from "@ant-design/icons/HomeOutlined";
export {default as PhoneOutlined} from "@ant-design/icons/PhoneOutlined";
export {default as TeamOutlined} from "@ant-design/icons/TeamOutlined";
export {default as MoreOutlined} from "@ant-design/icons/MoreOutlined";
export {default as GlobalOutlined} from "@ant-design/icons/GlobalOutlined";
export {default as BookOutlined} from "@ant-design/icons/BookOutlined";
export {default as WeiboOutlined} from "@ant-design/icons/WeiboOutlined";
export {default as SlidersOutlined} from "@ant-design/icons/SlidersOutlined";
export {faGraduationCap} from "@fortawesome/free-solid-svg-icons/faGraduationCap";
export {faPlaneDeparture} from "@fortawesome/free-solid-svg-icons/faPlaneDeparture";
export {faFile} from "@fortawesome/free-solid-svg-icons/faFile";
export {default as InboxOutlined} from "@ant-design/icons/InboxOutlined";
export {default as PlusOutlined} from "@ant-design/icons/PlusOutlined";
export {default as SyncOutlined} from "@ant-design/icons/SyncOutlined";
export {default as PlusCircleOutlined} from "@ant-design/icons/PlusCircleOutlined";
export {default as SettingOutlined} from "@ant-design/icons/SettingOutlined";
export {default as BranchesOutlined} from "@ant-design/icons/BranchesOutlined";
export {default as ReadOutlined} from "@ant-design/icons/ReadOutlined";
export {default as HeatMapOutlined} from "@ant-design/icons/HeatMapOutlined";
export {default as CalendarOutlined} from "@ant-design/icons/CalendarOutlined";
export {default as CodeSandboxOutlined} from "@ant-design/icons/CodeSandboxOutlined";
export {default as DownloadOutlined} from "@ant-design/icons/DownloadOutlined";
export {default as CloseOutlined} from "@ant-design/icons/CloseOutlined";
export {default as CommentOutlined} from "@ant-design/icons/CommentOutlined";
export {default as BellOutlined} from "@ant-design/icons/BellOutlined";
export {default as ExclamationCircleOutlined} from "@ant-design/icons/ExclamationCircleOutlined";
export {default as UserSwitchOutlined} from "@ant-design/icons/UserSwitchOutlined";
export {default as MinusCircleOutlined} from "@ant-design/icons/MinusCircleOutlined";
export {default as CheckOutlined} from "@ant-design/icons/CheckOutlined";
export {default as FileExcelOutlined} from "@ant-design/icons/FileExcelOutlined";
export {default as BarsOutlined} from "@ant-design/icons/BarsOutlined";
export {default as ApiOutlined} from "@ant-design/icons/ApiOutlined";
export {default as LeftCircleOutlined} from "@ant-design/icons/LeftCircleOutlined";
export {default as CloudDownloadOutlined} from "@ant-design/icons/CloudDownloadOutlined";
export {faClipboard} from "@fortawesome/free-solid-svg-icons/faClipboard";
export {faPaperclip} from "@fortawesome/free-solid-svg-icons/faPaperclip";